### ISSUE TITLE
Release v0.3.0

### ISSUE THREAD

**Issue by santisoler** [fatiando/dependente#9]
## Update the changelog

- [x] Generate a list of commits between the last release tag and now: `git log HEAD...v1.2.3 > changes.rst`
- [x] Edit the list to remove any trivial changes (updates by the bot, CI updates, etc).
- [x] Organize the list into categories (breaking changes, deprecations, bug fixes, new features, maintenance, documentation).
- [x] Add a list of people who contributed to the release: `git shortlog HEAD...v1.2.3 -sne`
- [x] Replace the PR numbers with links: ``sed --in-place "s,#\([0-9]\+\),\`#\1 <https://github.com/fatiando/PROJECT/pull/\1>\`__,g" changes.rst``
- [x] Check that you changed the ``PROJECT`` placeholder when running the last command.
- [x] Copy the changes to `CHANGELOG.md`
- [x] Add a link to the new release version documentation in `README.rst` and `doc/versions.rst` (if the file exists).
- [x] Open a PR to update the changelog
- [x] Merge the PR

## Make a release

After the changelog PR is merged:

- [x] Draft a new release on GitHub
- [x] The tag and release name should be a version number (following Semantic Versioning) with a leading `v` (`v1.5.7`)
- [x] Fill the release description with a Markdown version of the latest changelog entry (including the DOI badge)
- [x] Publish the release

## Conda-forge package

A PR should be opened automatically on the project feedstock repository.

- [x] Add/remove/update any dependencies that have changed in `meta.yaml`
- [x] If dropping/adding support for Python/numpy versions, make sure the correct version restrictions are applied in `meta.yaml`
- [x] Merge the PR

**Comment by leouieda** [comment]
Thanks for the release, Santi!

**Comment by santisoler** [comment]
No worries. Could you please check the conda-forge feedstock PR: https://github.com/conda-forge/dependente-feedstock/pull/2

Feel free to add me as maintainer if you want too.

**Comment by leouieda** [comment]
Merged! Could you open a PR on the feedstock adding yourself as maintainer?
